spring:
  datasource:
    user:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.2.21:3306/user
      username: root
      password: RepowebQuery123!
    business:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.2.21:3306/business
      username: root
      password: RepowebQuery123!
