spring:
  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

  datasource:
    user:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/user?characterEncoding=utf-8&autoReconnect=true
      username: root
      password: 123456
    business:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/business?characterEncoding=utf-8&autoReconnect=true
      username: root
      password: 123456
